# https://hub.docker.com/_/node/tags?name=slim
FROM docker.io/node:24-trixie-slim AS client-builder

ARG APP_HOME=/app
WORKDIR ${APP_HOME}

COPY ./package.json ${APP_HOME}
RUN npm install && npm cache clean --force
COPY . ${APP_HOME}
RUN npm run build

# https://hub.docker.com/_/python/tags?name=3.13
FROM docker.io/python:3.13-slim-trixie AS python

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ARG BUILD_ENVIRONMENT=local
ARG APP_HOME=/app

ENV BUILD_ENV=${BUILD_ENVIRONMENT}
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# https://docs.astral.sh/uv/guides/integration/docker/
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

# install required system dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
    # better utils if we need to run a shell in the container
    git bash-completion nano ssh htop \
    rsync net-tools wget curl jq nmap \
    # psycopg build
    build-essential \
    libpq-dev \
    # translations dependencies
    gettext \
    # hdf5 deps for digital-rf
    hdf5-tools \
    libhdf5-dev \
    libhdf5-serial-dev \
    python3-dev \
    python3-h5py \
    # purge cache to reduce image size
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*

# install rust toolchain for the `blake3` package
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    . $HOME/.cargo/env && \
    echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $HOME/.bashrc
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR ${APP_HOME}

# install project dependencies
COPY ./pyproject.toml ./uv.lock ${APP_HOME}/
RUN uv sync --frozen --extra ${BUILD_ENVIRONMENT}

# "entrypoint" only has a production version
COPY ./compose/production/django/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./compose/local/django/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

# copy application code to WORKDIR
COPY . ${APP_HOME}

ENTRYPOINT ["/entrypoint"]
