#!/bin/bash

set -euo pipefail

APP_DIR="/app"

# logs a message and waits for manual input before exiting and terminating the container
function echo_wait_and_quit() {
    local message="$1"
    echo >&2 "$message"

    # this wait may be useful for manually running manage.py or
    # other shell commands in the container in case of failure:
    echo -e >&2 "\033[0;31mGiving time for manual input before exiting...\033[0m"
    sleep 3600

    exit 1
}

function main() {

    pushd "${APP_DIR}" || {
        echo_wait_and_quit "Failed to change directory to ${APP_DIR}."
    }

    echo -e "\033[0;34mPreparing gateway...\033[0m"
    uv run manage.py prepare_gateway --pipeline-strategy=smart-recreate || {
        echo_wait_and_quit "Failed to prepare gateway for startup."
    }

    echo -e "\033[0;34mStarting Uvicorn server...\033[0m"
    exec uv run uvicorn config.asgi:application \
        --host 0.0.0.0 \
        --reload \
        --reload-include '*.html' || {
            echo_wait_and_quit "Uvicorn server failed."
        }

}

main "$@" || {
    echo >&2 "An error occurred while starting the Django application."
    exit 1
}
