---
# Example markdownlint configuration file:
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true
no-hard-tabs: true

# TIP: set any block to "false" to disable it

# TIP: on VS Code, use Ctrl+Space to see available rules and properties

# MD013: Line length
line-length: false
# line-length:
#     line_length: 119
#     heading_line_length: 119
#     code_block_line_length: 119
#     code_blocks: false
#     tables: false
#     headings: false
#     strict: false
#     stern: false

# MD024: Multiple headers with the same content
no-duplicate-heading:
    siblings_only: true

# MD029: Ordered list item prefix
ol-prefix:
    style: one_or_ordered

# MD030: Spaces after list markers
ul-indent:
    indent: 4
    start_indented: false
    start_indent: 4

# MD004: Header style
ul-style:
    style: consistent

# MD059: Link text should be descriptive
descriptive-link-text: false
