# ⚠️ PRODUCTION COMPOSE FILE ⚠️
# Make sure images, container names, and other assets start with "sds-gateway-prod-"
#   to underline its importance and avoid accidents.
# Also try to keep it as close to the production
#   file as possible to simplify the deployment process.

volumes:
    # for safety, all gateway production volumes start with "sds-gateway-prod-"
    sds-gateway-prod-postgres-data: {}
    sds-gateway-prod-postgres-data-backups: {}
    sds-gateway-prod-app-media: {}
    sds-gateway-prod-redis-data: {}
    sds-gateway-prod-minio-files: {}
    sds-gateway-prod-opensearch-data: {}

networks:
    # for safety, all gateway production networks start with "sds-gateway-prod-"
    sds-gateway-prod-minio-net:
        driver: bridge
    sds-gateway-prod-opensearch-net:
        driver: bridge
    sds-network-prod:
        external: true

services:

    sds-gateway-prod-app:
        build:
            context: .
            dockerfile: ./compose/production/django/Dockerfile
        image: sds-gateway-prod-app
        container_name: sds-gateway-prod-app
        tty: true
        depends_on:
            - postgres
            - redis
            - minio
        volumes:
            - sds-gateway-prod-app-media:/app/sds_gateway/media # used in prod only
        env_file:
            - ./.envs/production/django.env
            - ./.envs/production/minio.env
            - ./.envs/production/postgres.env
            - ./.envs/production/opensearch.env
        ports:
            - "18000:18000" # make sure this port matches traefik's config, if used
        command: /start
        networks:
            - sds-gateway-prod-opensearch-net
            - sds-gateway-prod-minio-net
            - sds-network-prod

    nginx:
        # nginx serves the static files generated for the gateway
        image: docker.io/nginx:1-alpine
        container_name: sds-gateway-prod-nginx
        volumes:
            - source : ./compose/production/nginx/nginx-default.conf
              target: /etc/nginx/conf.d/default.conf
              type: bind
              read_only: true
            # e.g. curl --insecure https://sds.crc.nd.edu/static/css/project.css
            # - source: ./nginx/data  # TODO: point to built static files
            - source: sds_gateway/static  # TODO: point to built static files
              target: /usr/share/nginx/static
              type: bind
              read_only: true
        networks:
            - sds-network-prod

    minio:
        # main file storage for sds
        # minio uses rolling upgrades that are non-disruptive, so we can target latest
        # For more information on how to upgrade MinIO deployment, refer to the MinIO documentation:
        # https://min.io/docs/minio/container/operations/install-deploy-manage/upgrade-minio-deployment.html
        image: minio/minio:latest
        container_name: sds-gateway-prod-minio
        volumes:
            - sds-gateway-prod-minio-files:/files
        ports:
            - "9000:9000"
            - "9001:9001"
        env_file:
            - ./.envs/production/minio.env
        command: server /files --console-address ":9001"
        networks:
            - sds-gateway-prod-minio-net

    opensearch:
        # used for indexing and searching documents
        # opensearch upgrades follow semver - let's target a major version
        # https://opensearch.org/docs/latest/install-and-configure/upgrade-opensearch/index/
        # release notes
        # https://opensearch.org/docs/latest/version-history/
        image: opensearchproject/opensearch:2
        container_name: sds-gateway-prod-opensearch
        volumes:
            - sds-gateway-prod-opensearch-data:/usr/share/opensearch/data
            - ./compose/production/opensearch/opensearch.yaml:/usr/share/opensearch/config/opensearch.yml
            - ./opensearch/data/certs:/usr/share/opensearch/config/certs
        env_file:
            - ./.envs/production/opensearch.env
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9600:9600"
        networks:
            - sds-gateway-prod-opensearch-net

    postgres:
        # main database for the gateway app
        build:
            context: .
            dockerfile: ./compose/production/postgres/Dockerfile
        image: sds-gateway-prod-postgres
        container_name: sds-gateway-prod-postgres
        volumes:
            - sds-gateway-prod-postgres-data:/var/lib/postgresql/data
            - sds-gateway-prod-postgres-data-backups:/backups
        env_file:
            - ./.envs/production/postgres.env
        networks:
            - sds-gateway-prod-minio-net

    redis:
        # used as caching layer for the gateway app
        image: docker.io/redis:6
        container_name: sds-gateway-prod-redis
        volumes:
            - sds-gateway-prod-redis-data:/data

    # ===================
    # production services
