volumes:
    sds_gateway_local_postgres_data: {}
    sds_gateway_local_postgres_data_backups: {}
    sds_gateway_local_redis_data: {}

services:
    django: &django
        build:
            context: .
            dockerfile: ./compose/local/django/Dockerfile
        image: sds_gateway_local_django
        container_name: sds_gateway_local_django
        depends_on:
            - postgres
            - redis
        volumes:
            - .:/app:z
        env_file:
            - ./.envs/local/django.env
            - ./.envs/local/postgres.env
        ports:
            - "8000:8000"
        command: /start

    postgres:
        build:
            context: .
            dockerfile: ./compose/production/postgres/Dockerfile
        image: sds_gateway_production_postgres
        container_name: sds_gateway_local_postgres
        volumes:
            - sds_gateway_local_postgres_data:/var/lib/postgresql/data
            - sds_gateway_local_postgres_data_backups:/backups
        env_file:
            - ./.envs/local/postgres.env

    redis:
        image: docker.io/redis:6
        container_name: sds_gateway_local_redis

        volumes:
            - sds_gateway_local_redis_data:/data

    celeryworker:
        <<: *django
        image: sds_gateway_local_celeryworker
        container_name: sds_gateway_local_celeryworker
        depends_on:
            - redis
            - postgres
        ports: []
        command: /start-celeryworker

    celerybeat:
        <<: *django
        image: sds_gateway_local_celerybeat
        container_name: sds_gateway_local_celerybeat
        depends_on:
            - redis
            - postgres
        ports: []
        command: /start-celerybeat

    flower:
        <<: *django
        image: sds_gateway_local_flower
        container_name: sds_gateway_local_flower
        ports:
            - "5555:5555"
        command: /start-flower

    node:
        build:
            context: .
            dockerfile: ./compose/local/node/Dockerfile
        image: sds_gateway_local_node
        container_name: sds_gateway_local_node
        depends_on:
            - django
        volumes:
            - .:/app:z
            # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
            - /app/node_modules
        command: npm run dev
        ports:
            - "3000:3000"
