# CI COMPOSE FILE
# Make sure images, container names, and other assets start with "sds-gateway-ci-"
#   to underline its importance and avoid accidents.
# Also try to keep it as close to the production
#   file as possible to simplify the deployment process.

volumes:
    # for safety, all local volumes start with "sds-gateway-ci-"
    sds-gateway-ci-app-media: {} # for Django media files
    sds-gateway-ci-temp-zips: {} # for temporary zip files
    sds-gateway-ci-uv-cache: {} # shared cache for uv
    sds-gateway-ci-uv-venv-app: {}
    sds-gateway-ci-uv-venv-worker: {}
    sds-gateway-ci-uv-venv-beat: {}
    sds-gateway-ci-uv-venv-flower: {}
    sds-gateway-ci-minio-files: {}
    sds-gateway-ci-opensearch-data: {}
    sds-gateway-ci-postgres-data-backups: {}
    sds-gateway-ci-postgres-data: {}
    sds-gateway-ci-redis-data: {}

networks:
    # for safety, all gateway local networks start with "sds-gateway-ci-"
    sds-gateway-ci-minio-net:
        driver: bridge
    sds-gateway-ci-opensearch-net:
        driver: bridge
    sds-network-ci:
        # external: true # make it external if running with traefik on this machine
        # should match traefik's network name
        name: sds-network-ci
        driver: bridge
services:
    sds-gateway-ci-app:
        build:
            context: .
            dockerfile: ./compose/local/django/Dockerfile
        image: sds-gateway-ci-app
        container_name: sds-gateway-ci-app
        tty: true # colored logs
        depends_on:
            opensearch:
                condition: service_healthy
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            minio:
                condition: service_healthy
        volumes:
            - sds-gateway-ci-uv-cache:/opt/uv-cache/
            - sds-gateway-ci-uv-venv-app:/opt/uv-venv/
            - sds-gateway-ci-app-media:/app/sds_gateway/media # persistent media storage
            - sds-gateway-ci-temp-zips:/app/sds_gateway/media/temp_zips # temporary zip files
            - source: ./sds_gateway/api_methods/migrations
              target: /app/sds_gateway/api_methods/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/users/migrations
              target: /app/sds_gateway/users/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/visualizations/migrations
              target: /app/sds_gateway/visualizations/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z

            # - ./staticfiles/:/app/staticfiles/:z  # used in prod only
        env_file:
            - ./.envs/ci/django.env
            - ./.envs/ci/minio.env
            - ./.envs/ci/postgres.env
            - ./.envs/ci/opensearch.env
        # remember /entrypoint runs first
        command: "/start"
        ports:
            - "8000:8000" # make sure this port matches traefik's config, if used
        networks:
            - sds-gateway-ci-minio-net
            - sds-gateway-ci-opensearch-net
            - sds-network-ci
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5
        develop:
            watch:
                - action: sync
                  path: .
                  target: /app
                  ignore:
                      - ".venv/**/*"
                      - "node_modules/**/*"
                      - "staticfiles/**/*"

                - action: rebuild
                  path: ./pyproject.toml

    nginx:
        # nginx serves the static files generated for the gateway
        image: docker.io/nginx:1-alpine
        container_name: sds-gateway-ci-nginx
        volumes:
            - source: ./compose/production/nginx/nginx-default.conf
              target: /etc/nginx/conf.d/default.conf
              type: bind
              read_only: true
              bind:
                  selinux: z
            # e.g. curl --insecure https://sds.crc.nd.edu/static/css/project.css
            # this location is only used in local; prod uses 'staticfiles/'
            - source: ./sds_gateway/static/
              target: /usr/share/nginx/static
              type: bind
              read_only: true
              bind:
                  selinux: z
        networks:
            - sds-network-ci

    minio:
        # main file storage for sds
        # minio uses rolling upgrades that are non-disruptive, so we can target latest
        # For more information on how to upgrade MinIO deployment, refer to the MinIO documentation:
        # https://min.io/docs/minio/container/operations/install-deploy-manage/upgrade-minio-deployment.html
        image: minio/minio:latest
        container_name: sds-gateway-ci-minio
        volumes:
            - sds-gateway-ci-minio-files:/files
        ports:
            - "9000:9000"
            - "9001:9001"
        env_file:
            - ./.envs/ci/minio.env
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -f http://localhost:9000/minio/health/live || exit 1",
                ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s
        command: 'server /files --console-address ":9001"'
        networks:
            - sds-gateway-ci-minio-net

    opensearch:
        # used for indexing and searching documents
        build:
            context: .
            dockerfile: ./compose/local/opensearch/Dockerfile
            args:
                UID: ${UID}
                GID: ${GID}
        container_name: sds-gateway-ci-opensearch
        volumes:
            - sds-gateway-ci-opensearch-data:/usr/share/opensearch/data
            - ./compose/local/opensearch/opensearch.yaml:/usr/share/opensearch/config/opensearch.yml
        env_file:
            - ./.envs/ci/opensearch.env
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9600:9600"
        networks:
            - sds-gateway-ci-opensearch-net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -u ${OPENSEARCH_USER}:${OPENSEARCH_PASSWORD} http://localhost:9200/_cluster/health?pretty | grep -q '\"status\" : \"green\"\\|\"status\" : \"yellow\"'",
                ]
            interval: 5s
            timeout: 5s
            retries: 10

    postgres:
        # main database for the gateway app
        build:
            context: .
            dockerfile: ./compose/production/postgres/Dockerfile
            # this dockerfile is used for both local and prod
        image: sds-gateway-ci-postgres
        container_name: sds-gateway-ci-postgres
        volumes:
            - sds-gateway-ci-postgres-data:/var/lib/postgresql/data
            - sds-gateway-ci-postgres-data-backups:/backups
        env_file:
            - ./.envs/ci/postgres.env
        networks:
            - sds-gateway-ci-minio-net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" -h localhost',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    redis:
        # used as caching layer for the gateway app
        image: docker.io/redis:6
        container_name: sds-gateway-ci-redis
        volumes:
            - sds-gateway-ci-redis-data:/data
        networks:
            - sds-network-ci
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s

    # ==========================
    # Celery services for background tasks
    celery-worker:
        build:
            context: .
            dockerfile: ./compose/local/django/Dockerfile
        image: sds-gateway-ci-app
        container_name: sds-gateway-ci-celery-worker
        tty: true
        depends_on:
            sds-gateway-ci-app:
                condition: service_healthy
        volumes:
            - sds-gateway-ci-uv-cache:/opt/uv-cache/
            - sds-gateway-ci-uv-venv-worker:/opt/uv-venv/
            - sds-gateway-ci-app-media:/app/sds_gateway/media # persistent media storage
            - sds-gateway-ci-temp-zips:/app/sds_gateway/media/temp_zips # temporary zip files
            - source: ./sds_gateway/api_methods/migrations
              target: /app/sds_gateway/api_methods/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/users/migrations
              target: /app/sds_gateway/users/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/visualizations/migrations
              target: /app/sds_gateway/visualizations/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
        env_file:
            - ./.envs/ci/django.env
            - ./.envs/ci/minio.env
            - ./.envs/ci/postgres.env
            - ./.envs/ci/opensearch.env
        command: "/worker-start"
        networks:
            - sds-gateway-ci-minio-net
            - sds-gateway-ci-opensearch-net
            - sds-network-ci

    celery-beat:
        # Celery Beat scheduler for periodic tasks
        build:
            context: .
            dockerfile: ./compose/local/django/Dockerfile
        image: sds-gateway-ci-app
        container_name: sds-gateway-ci-celery-beat
        tty: true
        depends_on:
            sds-gateway-ci-app:
                condition: service_healthy
        volumes:
            - sds-gateway-ci-uv-cache:/opt/uv-cache/
            - sds-gateway-ci-uv-venv-beat:/opt/uv-venv/
            - sds-gateway-ci-app-media:/app/sds_gateway/media # persistent media storage
            - sds-gateway-ci-temp-zips:/app/sds_gateway/media/temp_zips # temporary zip files
            - source: ./sds_gateway/api_methods/migrations
              target: /app/sds_gateway/api_methods/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/users/migrations
              target: /app/sds_gateway/users/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/visualizations/migrations
              target: /app/sds_gateway/visualizations/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
        env_file:
            - ./.envs/ci/django.env
            - ./.envs/ci/minio.env
            - ./.envs/ci/postgres.env
            - ./.envs/ci/opensearch.env
        command: "/beat-start"
        networks:
            - sds-gateway-ci-minio-net
            - sds-gateway-ci-opensearch-net
            - sds-network-ci

    celery-flower:
        # Celery monitoring and administration tool
        build:
            context: .
            dockerfile: ./compose/local/django/Dockerfile
        image: sds-gateway-ci-app
        container_name: sds-gateway-ci-celery-flower
        tty: true
        depends_on:
            sds-gateway-ci-app:
                condition: service_healthy
        volumes:
            - sds-gateway-ci-uv-cache:/opt/uv-cache/
            - sds-gateway-ci-uv-venv-flower:/opt/uv-venv/
            - sds-gateway-ci-app-media:/app/sds_gateway/media
            - sds-gateway-ci-temp-zips:/app/sds_gateway/media/temp_zips
            - source: ./sds_gateway/api_methods/migrations
              target: /app/sds_gateway/api_methods/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/users/migrations
              target: /app/sds_gateway/users/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
            - source: ./sds_gateway/visualizations/migrations
              target: /app/sds_gateway/visualizations/migrations
              type: bind
              read_only: false
              bind:
                  selinux: z
        env_file:
            - ./.envs/ci/django.env
            - ./.envs/ci/minio.env
            - ./.envs/ci/postgres.env
            - ./.envs/ci/opensearch.env
        command: "/flower-start"
        ports:
            - "5555:5555" # Flower web interface
        networks:
            - sds-gateway-ci-minio-net
            - sds-gateway-ci-opensearch-net
            - sds-network-ci

    # ==========================
    # local development services
    node:
        # used for frontend development and hot reloading
        build:
            context: .
            dockerfile: ./compose/local/node/Dockerfile
        image: sds-gateway-ci-node
        container_name: sds-gateway-ci-node
        networks:
            - sds-network-ci
        depends_on:
            - sds-gateway-ci-app
        volumes:
            # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
            - /app/node_modules
            # Bind mount project directory for running tests
            - source: .
              target: /app/
              type: bind
              bind:
                  selinux: z
        command: "npm run dev"
        ports:
            - "3000:3000"
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app/

    mailhog:
        # email testing service for local development
        image: mailhog/mailhog:latest
        container_name: sds-gateway-ci-mailhog
        ports:
            - "1025:1025" # SMTP server
            - "8025:8025" # Web UI
        networks:
            - sds-network-ci
