services:
    docs:
        image: sds_gateway_local_docs
        container_name: sds_gateway_local_docs
        build:
            context: .
            dockerfile: ./compose/local/docs/Dockerfile
        env_file:
            - ./.envs/local/django.env
        volumes:
            - ./docs:/docs:z
            - ./config:/app/config:z
            - ./sds_gateway:/app/sds_gateway:z
        ports:
            - "9000:9000"
        command: /start-docs
