# Generated by Django 4.2.14 on 2024-11-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved to use the API by an Admin.', verbose_name='Approved'),
        ),
    ]
