# Generated by Django 4.2.14 on 2025-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='source',
            field=models.CharField(choices=[('sds_web_ui', 'SDS Web UI'), ('sds_api', 'SDS API'), ('svi_backend', 'SVI Backend')], default='sds_web_ui', max_length=255),
        ),
    ]
