# Generated by Django 4.2.14 on 2025-01-21 15:12

from django.db import migrations
from django.conf import settings
import secrets
import string
from django.contrib.auth.hashers import make_password

def create_svi_api_key(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Token = apps.get_model('authtoken', 'Token')
    
    # create a new "SVI Server" user    
    user, created = User.objects.get_or_create(email=settings.SVI_SERVER_EMAIL)

    if created:
        password = ''.join(secrets.choice(string.ascii_letters + string.digits + string.punctuation) for _ in range(32))
        user.password = make_password(password)
        user.save()

    # Delete any existing tokens for this user
    Token.objects.filter(user=user).delete()

    # create a new authentication token for the SVI Server user
    Token.objects.create(user=user, key=settings.SVI_SERVER_API_KEY)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userapikey_source'),
        ('authtoken', '0003_tokenproxy'),  # Add dependency on authtoken
    ]

    operations = [
        migrations.RunPython(create_svi_api_key),
    ]
