# Generated by Django 4.2.14 on 2025-01-31 02:10

from django.db import migrations, models
import sds_gateway.api_methods.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250121_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='source',
            field=models.CharField(choices=[(sds_gateway.api_methods.models.KeySources['SDSWebUI'], 'SDS Web UI'), (sds_gateway.api_methods.models.KeySources['SVIBackend'], 'SVI Backend'), (sds_gateway.api_methods.models.KeySources['SVIWebUI'], 'SVI Web UI')], default=sds_gateway.api_methods.models.KeySources['SDSWebUI'], max_length=255),
        ),
    ]
