# Generated by Django 4.2.14 on 2025-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250121_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='svi_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
