# Generated by Django 4.2.14 on 2025-01-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_svi_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='svi_api_key',
        ),
    ]
