# Generated by Django 4.2.14 on 2025-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this API key (e.g., device info, experiment info).', null=True),
        ),
    ]
