# Generated by Django 4.2.14 on 2025-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved to use the API by an Admin.', verbose_name='Approved'),
        ),
    ]
