# Generated by Django 4.2.14 on 2025-06-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userapikey_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={},
        ),
        migrations.AddConstraint(
            model_name='userapikey',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_api_key_name'),
        ),
    ]
