# Generated by Django 4.2.14 on 2025-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this API key.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Designates whether this user has been approved to use the API by an Admin.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
