# Generated by Django 4.2.14 on 2025-06-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userapikey_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key Name'),
        ),
    ]
