# Generated by Django 4.2.14 on 2025-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userapikey_description_and_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ORCID ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Designates whether this user has been approved to use the API by an Admin.', verbose_name='Approved'),
        ),
    ]
