# Generated by Django 4.2.14 on 2025-09-04 12:52

from django.db import migrations, models
from ..validators import validate_orcid_id


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userapikey_description_and_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orcid_id',
            field=models.CharField(
                blank=True, 
                max_length=19, 
                validators=[validate_orcid_id],
                verbose_name='ORCID ID'
            ),
        ),
    ]
