# Generated by Django 4.2.14 on 2025-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userapikey_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={'ordering': ('-created',), 'verbose_name': 'API key', 'verbose_name_plural': 'API keys'},
        ),
        migrations.RemoveConstraint(
            model_name='userapikey',
            name='unique_user_api_key_name',
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
