# Generated by Django 4.2.14 on 2025-06-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userapikey_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this API key.', null=True),
        ),
    ]
