# Generated by Django 4.2.14 on 2025-07-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_approved'),
        ('users', '0013_alter_userapikey_description'),
    ]

    operations = [
    ]
