# Generated by Django 4.2.14 on 2025-08-28 22:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_methods', '0011_post_processed_data_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProcessedData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('processing_type', models.CharField(choices=[('waterfall', 'Waterfall'), ('spectrogram', 'Spectrogram')], help_text='Type of post-processing (waterfall, spectrogram, etc.)', max_length=50)),
                ('processing_parameters', models.JSONField(default=dict, help_text='Processing parameters (FFT size, window type, etc.)')),
                ('data_file', models.FileField(blank=True, help_text='File containing the processed data', null=True, upload_to='post_processed_data/')),
                ('metadata', models.JSONField(default=dict, help_text='Processing metadata (frequencies, timestamps, etc.)')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the processing was completed', null=True)),
                ('pipeline_id', models.CharField(blank=True, help_text='Cog pipeline ID for tracking', max_length=255)),
                ('capture', models.ForeignKey(help_text='The capture this processed data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='visualization_post_processed_data', to='api_methods.capture')),
            ],
            options={
                'verbose_name_plural': 'Post processed data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['capture', 'processing_type'], name='visualizati_capture_d5fac9_idx'), models.Index(fields=['processing_status'], name='visualizati_process_fe60db_idx'), models.Index(fields=['pipeline_id'], name='visualizati_pipelin_c2b254_idx')],
                'unique_together': {('capture', 'processing_type', 'processing_parameters')},
            },
        ),
    ]
