# Generated by Django 4.2.14 on 2025-09-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postprocesseddata',
            unique_together=set(),
        ),
    ]
