# Generated by Django 4.2.25 on 2025-10-31 16:33

from django.db import migrations, models
import django.db.models.deletion
import json


def copy_text_to_json(apps, schema_editor):
    """Copy existing text data to JSON field format."""
    PostProcessedData = apps.get_model('visualizations', 'PostProcessedData')

    for obj in PostProcessedData.objects.all():
        if obj.processing_error:
            # Handle empty strings - convert to None
            if isinstance(obj.processing_error, str) and not obj.processing_error.strip():
                obj.processing_error_temp = None
                obj.save(update_fields=['processing_error_temp'])
                continue

            try:
                # Try to parse as JSON first
                parsed = json.loads(obj.processing_error)
                # If it parses, use the parsed JSON
                obj.processing_error_temp = parsed
            except (json.JSONDecodeError, ValueError):
                # It's not JSON, convert it to JSON format
                obj.processing_error_temp = {
                    "traceback": obj.processing_error,
                }
            obj.save(update_fields=['processing_error_temp'])


def reverse_copy(apps, schema_editor):
    """Reverse: Copy from JSON back to text format."""
    PostProcessedData = apps.get_model('visualizations', 'PostProcessedData')

    for obj in PostProcessedData.objects.all():
        if obj.processing_error_temp:
            if isinstance(obj.processing_error_temp, dict):
                traceback = obj.processing_error_temp.get('traceback') or str(obj.processing_error_temp)
                obj.processing_error = traceback
            else:
                obj.processing_error = str(obj.processing_error_temp)
            obj.save(update_fields=['processing_error'])


class Migration(migrations.Migration):

    replaces = [('visualizations', '0003_postprocesseddata_cog_error_and_more'), ('visualizations', '0004_alter_postprocesseddata_metadata_and_more')]

    dependencies = [
        ('visualizations', '0002_alter_postprocesseddata_unique_together'),
        ('django_cog', '0002_pipelinerun_arguments_as_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprocesseddata',
            name='processing_error_temp',
            field=models.JSONField(blank=True, help_text='Error information if processing failed', null=True),
        ),
        migrations.RunPython(
            code=copy_text_to_json,
            reverse_code=reverse_copy,
        ),
        migrations.RemoveField(
            model_name='postprocesseddata',
            name='processing_error',
        ),
        migrations.RenameField(
            model_name='postprocesseddata',
            old_name='processing_error_temp',
            new_name='processing_error',
        ),
        migrations.AddField(
            model_name='postprocesseddata',
            name='cog_error',
            field=models.ForeignKey(blank=True, help_text='Django COG error record, if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_cog.cogerror'),
        ),
        migrations.AlterField(
            model_name='postprocesseddata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Processing metadata (frequencies, timestamps, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='postprocesseddata',
            name='processing_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Processing parameters (FFT size, window type, etc.)', null=True),
        ),
    ]
