# Generated by Django 4.2.14 on 2025-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_alter_postprocesseddata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprocesseddata',
            name='processing_type',
            field=models.CharField(choices=[('waterfall', 'Waterfall'), ('waterfall_low_res', 'Waterfall_Low_Res'), ('spectrogram', 'Spectrogram')], help_text='Type of post-processing (waterfall, spectrogram, etc.)', max_length=50),
        ),
    ]
