# Generated by Django 4.2.25 on 2025-10-27 20:01

from django.db import migrations, models
import django.db.models.deletion
import json


def convert_text_to_json(apps, schema_editor):
    """Convert existing text data to JSON format."""
    PostProcessedData = apps.get_model('visualizations', 'PostProcessedData')

    for obj in PostProcessedData.objects.all():
        if obj.processing_error and isinstance(obj.processing_error, str):
            # Handle empty strings - convert to None
            if not obj.processing_error.strip():
                obj.processing_error = None
                obj.save(update_fields=['processing_error'])
                continue

            try:
                # Try to parse as JSON first
                json.loads(obj.processing_error)
                # If it parses, it's already JSON - no conversion needed
            except (json.JSONDecodeError, ValueError):
                # It's not JSON, convert it to JSON format
                obj.processing_error = {
                    "traceback": obj.processing_error,
                }
                obj.save(update_fields=['processing_error'])


def reverse_convert(apps, schema_editor):
    """Reverse: Extract traceback from JSON."""
    PostProcessedData = apps.get_model('visualizations', 'PostProcessedData')

    for obj in PostProcessedData.objects.all():
        if obj.processing_error:
            if isinstance(obj.processing_error, dict):
                traceback = obj.processing_error.get('traceback') or str(obj.processing_error)
                obj.processing_error = traceback
                obj.save(update_fields=['processing_error'])


class Migration(migrations.Migration):

    dependencies = [
        ('django_cog', '0002_pipelinerun_arguments_as_json'),
        ('visualizations', '0002_alter_postprocesseddata_unique_together'),
    ]

    operations = [
        # Step 1: Make the TextField nullable first
        migrations.AlterField(
            model_name='postprocesseddata',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error information if processing failed', null=True),
        ),

        # Step 2: Convert text data to JSON format
        migrations.RunPython(convert_text_to_json, reverse_convert),

        # Step 3: Now alter the field type from TextField to JSONField
        migrations.AlterField(
            model_name='postprocesseddata',
            name='processing_error',
            field=models.JSONField(blank=True, help_text='Error information if processing failed', null=True),
        ),

        # Step 4: Add the cog_error field
        migrations.AddField(
            model_name='postprocesseddata',
            name='cog_error',
            field=models.ForeignKey(blank=True, help_text='Django COG error record, if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_cog.cogerror'),
        ),
    ]
