# Generated by Django 4.2.25 on 2025-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0003_postprocesseddata_cog_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprocesseddata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Processing metadata (frequencies, timestamps, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='postprocesseddata',
            name='processing_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Processing parameters (FFT size, window type, etc.)', null=True),
        ),
    ]
