services:

    traefik:
        image: docker.io/traefik:3
        volumes:
            - source: ./traefik/data/acme
              target: /etc/traefik/acme
              type: bind
              read_only: false
            - source: ./traefik/data/certs
              target: /etc/traefik/certs
              type: bind
              read_only: true
            - source: ./traefik/traefik.toml
              target: /etc/traefik/traefik.toml
              type: bind
              read_only: true
            - source: ./traefik/credentials.htpasswd
              target: /etc/traefik/dashboard/credentials.htpasswd
              type: bind
              read_only: true
        networks:
            - sds-network
        expose:
            - "80" # nginx, whoami, gateway
            - "443" # nginx, whoami, gateway
            - "5555" # flower
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            - "0.0.0.0:5555:5555"

    # nginx serves the static files generated for the gateway
    nginx:
        image: docker.io/nginx:1-alpine
        volumes:
            - source : ./nginx/nginx-default.conf
              target: /etc/nginx/conf.d/default.conf
              type: bind
              read_only: true
            # e.g. curl --insecure https://sds.crc.nd.edu/static/css/project.css
            # - source: ./nginx/data  # TODO: point to built static files
            - source: ../gateway/sds_gateway/static  # TODO: point to built static files
              target: /usr/share/nginx/static
              type: bind
              read_only: true
        networks:
            - sds-network

    # whoami service to test traefik reachability
    # curl --insecure https://whoami.sds.crc.nd.edu
    whoami:
        image: traefik/whoami
        command:
            - --port=2001   # must match port in traefik.toml
            # - --name=sds-01
        networks:
            - sds-network

networks:
    sds-network:
        driver: bridge
        name: sds-network
