services:

    traefik:
        image: docker.io/traefik:3
        volumes:

            # ACME certificates from Let's Encrypt
            - source: ./traefik/data/acme
              target: /etc/traefik/acme
              type: bind
              read_only: false

            # user (self-signed or custom) certificates
            - source: ./traefik/data/certs
              target: /etc/traefik/certs
              type: bind
              read_only: true

            # traefik live-reloads this configuration file on changes
            - source: ./traefik/traefik.toml
              target: /etc/traefik/traefik.toml
              type: bind
              read_only: true

            - source: ./traefik/credentials.htpasswd
              target: /etc/traefik/dashboard/credentials.htpasswd
              type: bind
              read_only: true

        networks:
            - sds-network-local
            - sds-network-prod
        expose:
            - "80"  # redirects to https at 443 - see traefik.toml
            - "443"
        ports:
            # these allow traefik to listen on all interfaces
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"

    # whoami service to test traefik reachability
    # curl --insecure https://whoami.sds.crc.nd.edu
    whoami:
        image: traefik/whoami
        command:
            - --port=2001   # must match port in traefik.toml
            # - --name=sds-01
        networks:
            - sds-network-local

networks:

    # services in the same network are visible to each other

    # LOCAL
    sds-network-local:
        name: sds-network-local

    # ⚠️ PROD
    sds-network-prod:
        name: sds-network-prod
