services:

    traefik:
        image: docker.io/traefik:3
        volumes:
            - source: ./traefik/data/acme
              target: /etc/traefik/acme
              type: bind
              read_only: false
            - source: ./traefik/data/certs
              target: /etc/traefik/certs
              type: bind
              read_only: true
            - source: ./traefik/traefik.toml
              target: /etc/traefik/traefik.toml
              type: bind
              read_only: true
            - source: ./traefik/credentials.htpasswd
              target: /etc/traefik/dashboard/credentials.htpasswd
              type: bind
              read_only: true
        networks:
            - sds-network
        expose:
            - "80" # nginx, whoami, gateway
            - "443" # nginx, whoami, gateway
            - "5555" # flower
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            - "0.0.0.0:5555:5555"

    # whoami service to test traefik reachability
    # curl --insecure https://whoami.sds.crc.nd.edu
    whoami:
        image: traefik/whoami
        command:
            - --port=2001   # must match port in traefik.toml
            # - --name=sds-01
        networks:
            - sds-network

networks:
    sds-network-local:
        driver: bridge
        name: sds-network-local
    sds-network-prod:
        driver: bridge
        name: sds-network-local
