#!/bin/bash

set -o errexit
set -o nounset

# for cli options, run:
# uvx watchfiles --help
exec uv run watchfiles \
    'celery.__main__.main' \
    --filter 'python' \
    --args '-A config.celery_app worker -l INFO'
