# ⚠️ PRODUCTION CONFIG FILE ⚠️
# Saved changes are live immediately

# Traefik configuration file. Sample at:
# https://github.com/traefik/traefik/blob/master/traefik.sample.toml

[global]
    checkNewVersion    = true
    sendAnonymousUsage = false

# https://doc.traefik.io/traefik/operations/dashboard/
[api]
    # e.g. curl --insecure https://localhost/dashboard/
    dashboard = true
    # insecure  = true

[providers.file]
    # Dynamic routes live under conf.d (mounted in network/compose.yaml)
    directory = "/etc/traefik/conf.d"
    watch     = true

[accesslog]
    addInternals = true

    [accesslog.filters]
        minDuration   = "10ms"
        retryAttempts = true
        # statusCodes   = ["200", "300-302"] # switch to this if the one below is too verbose
        statusCodes   = ["200", "300-302", "400-404", "500-504"]  # dev

[log]
    level = "DEBUG"

[tls]
    [[tls.certificates]]
        certFile = "/etc/traefik/certs/public_key.crt"
        keyFile  = "/etc/traefik/certs/private_key.pem"
        stores   = ["default"]

    [tls.options]
        [tls.options.default]
            minVersion = "VersionTLS12"

    [tls.stores]

        # these self-signed certs will be used by default if let's encrypt
        #   fails due to e.g. the domain not being publicly reachable.
        # you might need --insecure flag in curl; and to manually bypass
        #   the browser's security warning if this is the case.
        [tls.stores.default]
            [tls.stores.default.defaultCertificate]
                certFile = "/etc/traefik/certs/public_key.crt"
                keyFile  = "/etc/traefik/certs/private_key.pem"

[entryPoints]
    # https://doc.traefik.io/traefik/routing/entrypoints/

    [entryPoints.web]
        address = ":80"

        [entryPoints.web.http.redirections.entryPoint]
            # redirect all HTTP traffic to HTTPS
            to = "web-secure"

    [entryPoints.web-secure]
        address   = ":443"
        asDefault = true

        [entryPoints.web-secure.http2]
            maxConcurrentStreams = 250

        [entryPoints.web-secure.http3]

[certificatesResolvers]
    [certificatesResolvers.letsencrypt]
        [certificatesResolvers.letsencrypt.acme]
            email   = "crc-sds-list@nd.edu"
            storage = "/etc/traefik/acme/acme.json"  # in traefik v3 this file doesn't need to be created manually

            [certificatesResolvers.letsencrypt.acme.httpChallenge]
                entryPoint = "web"
