# Traefik configuration file
# https://github.com/traefik/traefik/blob/master/traefik.sample.toml

[global]
    checkNewVersion    = true
    sendAnonymousUsage = false

# https://doc.traefik.io/traefik/operations/dashboard/
[api]
    # curl --insecure https://localhost/dashboard/
    dashboard = true
    # insecure  = true

[accesslog]
    addInternals = true

    [accesslog.filters]
        minDuration   = "10ms"
        retryAttempts = true
        # statusCodes   = ["200", "300-302"] # prod
        statusCodes = ["200", "300-302", "400-404", "500-504"] # dev

[log]
    level = "TRACE"

[tls]

    [[tls.certificates]]
        certFile = "/etc/traefik/certs/public_key.crt"
        keyFile  = "/etc/traefik/certs/private_key.pem"
        stores   = ["default"]

    [tls.options]

        [tls.options.default]
            minVersion = "VersionTLS12"

[tls.stores]
    [tls.stores.default]
        [tls.stores.default.defaultCertificate]
            certFile = "/etc/traefik/certs/public_key.crt"
            keyFile  = "/etc/traefik/certs/private_key.pem"

[entryPoints]

    # https://doc.traefik.io/traefik/routing/entrypoints/

    [entryPoints.web]
        address = ":80"
        [entryPoints.web.http.redirections.entryPoint]
            to = "web-secure"

[entryPoints.web-secure]
    address   = ":443"
    asDefault = true
    [entryPoints.web-secure.http2]
        maxConcurrentStreams = 250
    [entryPoints.web-secure.http3]

[entryPoints.flower]
    address = ":5555"

[certificatesResolvers]
    [certificatesResolvers.letsencrypt]
        [certificatesResolvers.letsencrypt.acme]
            email   = "crcsupport@nd.edu"
            storage = "/etc/traefik/acme/acme.json" # in traefik v3 this file doesn't need to be created manually
            [certificatesResolvers.letsencrypt.acme.httpChallenge]
                entryPoint = "web"

[http.routers]

    [http.routers.traefik-api]
        middlewares = ["auth"]
        rule        = "Host(`sds.crc.nd.edu`) && ( PathPrefix(`/dashboard/`) )"
        service     = "api@internal"
        [http.routers.traefik-api.tls]
            certResolver = "letsencrypt"

    [http.routers.sds-gateway-app]
        entryPoints = ["web", "web-secure"]
        middlewares = ["csrf"]
        rule        = "Host(`sds.crc.nd.edu`)"
        service     = "sds-gateway-app"
        [http.routers.sds-gateway-app.tls]
            certResolver = "letsencrypt"

# [http.routers.sds-gateway-static]
#     entryPoints = ["web", "web-secure"]
#     rule        = "Host(`sds.crc.nd.edu`) && PathPrefix(`/static/`)"
#     service     = "sds-gateway-static"
#     [http.routers.sds-gateway-static.tls]

[http.routers.flower-secure-router]
    entryPoints = ["flower"]
    rule        = "Host(`sds.crc.nd.edu`)"
    service     = "flower"
    [http.routers.flower-secure-router.tls]
        certResolver = "letsencrypt"

# [http.routers.whoami]
#     entryPoints = ["web", "web-secure"]
#     rule    = "Host(`sds.crc.nd.edu`)"
#     service = "whoami"
#     [http.routers.whoami.tls]
#         certResolver = "letsencrypt"

[http.middlewares]

    [http.middlewares.csrf]

        [http.middlewares.csrf.headers]
            hostsProxyHeaders = ["X-CSRFToken"]

[http.middlewares.auth]

    [http.middlewares.auth.basicAuth]
        # Generate the credentials file:
        #     $ htpasswd -nB your-user-name >> traefik/credentials.htpasswd
        # Try it out:
        #     $ e.g. curl -u your-user-name:your-password http://your-sds-hostname/dashboard/
        # https://doc.traefik.io/traefik/middlewares/http/basicauth/#usersfile
        usersFile = "/etc/traefik/dashboard/credentials.htpasswd"

[http.services]

    [[http.services.sds-gateway-app.loadBalancer.servers]]
        url = "http://sds-gateway-app:8000" # compose service name, in same network

    [[http.services.sds-gateway-static.loadBalancer.servers]]
        url = "http://nginx:80"

    [[http.services.flower.loadBalancer.servers]]
        url = "http://flower:5555"

    [[http.services.whoami.loadBalancer.servers]]
        url = "http://whoami:2001"

[providers.file]
    filename = "/etc/traefik/traefik.toml"
    watch    = true
