# LOCAL COMPOSE FILE
# Make sure images, container names, and other assets start with "sds-jupyter-local-"
#   to underline its importance and avoid accidents.
# Also try to keep it as close to the production
#   file as possible to simplify the deployment process.

volumes:
    # for safety, all local volumes start with "sds-jupyter-local-"
    sds-jupyter-local-data: {}

networks:
    # for safety, all local networks start with "sds-jupyter-local-"
    sds-jupyter-local-net-clients:
        driver: bridge

services:
    jupyter:
        build:
            context: .
            dockerfile: ./compose/local/jupyter/Dockerfile
            args:
                JUPYTERHUB_VERSION: latest
                NB_UID: ${NB_UID:-1000}
                NB_GID: ${NB_GID:-100}
                DOCKER_GID: ${DOCKER_GID:-103}
        restart: unless-stopped
        image: sds-jupyter-local
        container_name: sds-jupyter-local
        tty: true # for colored logs
        networks:
            sds-jupyter-local-net-clients:
                aliases:
                    - jupyterhub
        volumes:
            - "./compose/local/jupyter/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
            - "./compose/local/jupyter/sample_scripts:/srv/jupyter/sample_scripts:ro"
            - type: volume
              source: sds-jupyter-local-data
              target: /data
              read_only: false
            - type: bind
              source: /var/run/docker.sock
              target: /run/docker.sock
              read_only: false

        privileged: false

        user: "${NB_UID:-1000}:${DOCKER_GID:-103}"
        userns_mode: "host"
        ports:
            - "8888:8000"
        env_file:
            - ./.envs/local/jupyterhub.env
        environment:
            JUPYTERHUB_ADMIN: admin
            COMPOSE_PROJECT_NAME: sds-jupyter-local
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.jupyter-stripprefix.stripprefix.prefixes=/notebook"
            - "traefik.http.routers.sds-jupyter-local.entrypoints=web,web-secure"
            - "traefik.http.routers.sds-jupyter-local.middlewares=jupyter-stripprefix"
            - "traefik.http.routers.sds-jupyter-local.rule=Host(`sds-dev.crc.nd.edu`) && PathPrefix(`/notebook`)"
            - "traefik.http.routers.sds-jupyter-local.tls.certresolver=letsencrypt"
            - "traefik.http.routers.sds-jupyter-local.tls=true"
            - "traefik.http.services.sds-jupyter-local.loadbalancer.server.port=8000"
