# ⚠️ PRODUCTION COMPOSE FILE ⚠️
# Make sure images, container names, and other assets start with "sds-jupyter-prod-"
#   to underline its importance and avoid accidents.
# Also try to keep it as close to the production
#   file as possible to simplify the deployment process.

volumes:
    # for safety, all production volumes start with "sds-jupyter-prod-"
    sds-jupyter-prod-data: {}

networks:
    # for safety, all production networks start with "sds-jupyter-prod-"
    sds-jupyter-prod-net-clients:
        driver: bridge

services:
    jupyter:
        build:
            context: .
            dockerfile: ./compose/production/jupyter/Dockerfile
            args:
                JUPYTERHUB_VERSION: latest
                NB_UID: ${NB_UID:-1000}
                NB_GID: ${NB_GID:-100}
                DOCKER_GID: ${DOCKER_GID:-103}
        restart: unless-stopped
        image: sds-jupyter-prod
        container_name: sds-jupyter-prod
        tty: true # for colored logs
        networks:
            sds-jupyter-prod-net-clients:
                aliases:
                    - jupyterhub
        volumes:
            - "./compose/production/jupyter/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
            - "./compose/production/jupyter/sample_scripts:/srv/jupyter/sample_scripts:ro"
            - type: volume
              source: sds-jupyter-prod-data
              target: /data
              read_only: false
            - type: bind
              source: /var/run/docker.sock
              target: /run/docker.sock

        privileged: false

        userns_mode: "host"
        user: "${NB_UID:-1000}:${DOCKER_GID:-103}"
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        cap_add:
            # Required capabilities for JupyterHub user container management
            - SETUID # Allow changing effective user ID for container operations
            - SETGID # Allow changing effective group ID for container operations
        ports:
            - "18888:8000"
        env_file:
            - ./.envs/production/jupyterhub.env
        environment:
            JUPYTERHUB_ADMIN: admin
            COMPOSE_PROJECT_NAME: sds-jupyter-prod
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.jupyter-stripprefix.stripprefix.prefixes=/notebook"
            - "traefik.http.routers.sds-jupyter-prod.entrypoints=web,web-secure"
            - "traefik.http.routers.sds-jupyter-prod.middlewares=jupyter-stripprefix"
            - "traefik.http.routers.sds-jupyter-prod.rule=Host(`sds.crc.nd.edu`) && PathPrefix(`/notebook`)"
            - "traefik.http.routers.sds-jupyter-prod.tls.certresolver=letsencrypt"
            - "traefik.http.routers.sds-jupyter-prod.tls=true"
            - "traefik.http.services.sds-jupyter-prod.loadbalancer.server.port=8000"
