_meta:
  type: "roles"
  config_version: 2

client_access:
  description: "Read-write role for application access"
  reserved: false
  static: false
  cluster_permissions:
    - "cluster:monitor/*"
    - "cluster:admin/indices*"
    - "cluster:admin/index*"
    - "cluster:monitor/main"
    - "indices:data/write/bulk"
    - "indices:data/write/index"
  index_permissions:
    - index_patterns:
        - "captures-*"
      allowed_actions:
        - "indices:admin/*"
        - "indices:data/*"
        - "indices:monitor/*"
        - "indices:data/write/bulk"
        - "indices:data/write/index"
