#!/bin/bash

set -euo pipefail

APP_DIR="/app"

# logs a message and waits for manual input before exiting and terminating the container
function echo_wait_and_quit() {
    local message="$1"
    echo >&2 "$message"

    # this wait may be useful for manually running manage.py or
    # other shell commands in the container in case of failure:
    echo -e >&2 "\033[0;31mGiving time for manual input before exiting...\033[0m"
    sleep 3600

    exit 1
}

function main() {

    pushd "${APP_DIR}" || {
        echo_wait_and_quit "Failed to change directory to ${APP_DIR}."
    }

    echo -e "\033[0;34mCollecting static files...\033[0m"
    uv run manage.py collectstatic --noinput || {
        echo_wait_and_quit "Failed to collect static files."
    }

    echo -e "\033[0;34mApplying database migrations...\033[0m"
    uv run manage.py migrate --noinput || {
        echo_wait_and_quit "Failed to apply database migrations."
    }

    echo -e "\033[0;34mInitializing OpenSearch indices...\033[0m"
    uv run manage.py init_indices || {
        echo_wait_and_quit "Failed to initialize OpenSearch indices."
    }

    echo -e "\033[0;34mInitializing SVI server token...\033[0m"
    uv run manage.py init_svi_token || {
        echo_wait_and_quit "Failed to initialize SVI server token."
    }

    echo -e "\033[0;34mSetting up django-cog pipelines...\033[0m"
    uv run manage.py setup_pipelines --strategy=skip-if-exists || {
        echo_wait_and_quit "Failed to set up django-cog pipelines."
    }

    echo -e "\033[0;34mStarting Gunicorn server...\033[0m"
    exec uv run gunicorn config.asgi \
        --bind 0.0.0.0:18000 \
        --chdir=/app -k uvicorn_worker.UvicornWorker || {
            echo_wait_and_quit "Gunicorn server failed."
        }

}

main "$@" || {
    echo >&2 "An error occurred while starting the Django application."
    exit 1
}
