# Source:   https://tombi-toml.github.io/tombi/docs/configuration
toml-version = "v1.0.0"

[files]
    include = ["**/*.toml"]
    exclude = [".cache/**/*.toml"]

[format]
    [format.rules]
        array-bracket-space-width         = 0
        array-comma-space-width           = 1
        date-time-delimiter               = "T"
        group-blank-lines-limit           = 1
        indent-style                      = "space"
        indent-sub-tables                 = true
        indent-table-key-value-pairs      = true
        indent-width                      = 4
        inline-table-brace-space-width    = 1
        inline-table-comma-space-width    = 1
        key-value-equals-sign-alignment   = true
        key-value-equals-sign-space-width = 1
        line-ending                       = "lf"
        line-width                        = 88
        string-quote-style                = "double"
        table-blank-lines                 = 1
        trailing-comment-alignment        = true
        trailing-comment-space-width      = 2

[lint]
    [lint.rules]
        dotted-keys-out-of-order = "warn"
        key-empty                = "warn"
        tables-out-of-order      = "warn"

[lsp]
    code-action.enabled          = true
    completion.enabled           = true
    diagnostic.enabled           = true
    document-link.enabled        = true
    formatting.enabled           = true
    goto-declaration.enabled     = true
    goto-definition.enabled      = true
    goto-type-definition.enabled = true
    hover.enabled                = true
    workspace-diagnostic.enabled = true

[schema]
    enabled = true
    strict  = true
    catalog = {
        paths = [
            "tombi://www.schemastore.org/api/json/catalog.json",
            "https://www.schemastore.org/api/json/catalog.json",
        ]
    }

    # # Root Schema
    # [[schemas]]
    #     toml-version = "v1.0.0"
    #     path         = "https://example.com/schema.json"
    #     include      = ["example.toml"]

    # [schemas.format.rules]
    #         array-values-order.enabled = true
    #         table-keys-order.enabled   = true

    # [schemas.lint.rules]
    #         deprecated = "warn"
    #     overrides = [
    #         {
    #             targets = ["", "tool.*"],
    #             "format.rules.array-values-order" = "ascending",
    #             "format.rules.table-keys-order" = "ascending",
    #             "lint.rules.deprecated" = "warn",
    #         },
    #     ]

# Sub Schema
[[schemas]]
    root    = "tool.taskipy"
    path    = "schemas/partial-taskipy.schema.json"
    include = ["pyproject.toml"]

    [schemas.lint.rules]
        deprecated = "warn"

# Override config
[[overrides]]
    [overrides.files]
        include = ["specific/**/*.toml"]
        exclude = ["specific/**/ignored.toml"]

    [overrides.format]
        enabled = true

        [overrides.format.rules]
            array-bracket-space-width         = 1
            array-comma-space-width           = 1
            date-time-delimiter               = "space"
            group-blank-lines-limit           = 1
            indent-style                      = "tab"
            indent-sub-tables                 = true
            indent-table-key-value-pairs      = true
            indent-width                      = 4
            inline-table-brace-space-width    = 0
            inline-table-comma-space-width    = 1
            key-value-equals-sign-alignment   = true
            key-value-equals-sign-space-width = 1
            line-ending                       = "crlf"
            line-width                        = 120
            string-quote-style                = "single"
            table-blank-lines                 = 1
            trailing-comment-alignment        = true
            trailing-comment-space-width      = 1

    [overrides.lint]
        enabled = true

        [overrides.lint.rules]
            dotted-keys-out-of-order = "error"
            key-empty                = "error"
            tables-out-of-order      = "error"

[extensions]
    "tombi-toml/cargo"     = {
        lsp = {
            code-action      = {
                add-to-workspace-and-inherit-dependency.enabled = true,
                convert-dependency-to-table-format.enabled      = true,
                inherit-dependency-from-workspace.enabled       = true,
                inherit-from-workspace.enabled                  = true,
            },
            completion       = {
                dependency-feature.enabled = true,
                dependency-version.enabled = true,
                path.enabled               = true,
            },
            document-link    = {
                cargo-toml.enabled = true,
                crates-io.enabled  = true,
                git.enabled        = true,
                path.enabled       = true,
            },
            goto-declaration = {
                dependency.enabled = true,
                member.enabled     = true,
                path.enabled       = true,
            },
            goto-definition  = {
                dependency.enabled = true,
                member.enabled     = true,
                path.enabled       = true,
            },
            hover            = {
                dependency-detail.enabled = true,
            },
            inlay-hint       = {
                default-features.enabled   = true,
                dependency-version.enabled = true,
                workspace-value.enabled    = true,
            },
        }
    }
    "tombi-toml/pyproject" = {
        lsp = {
            code-action      = {
                add-to-workspace-and-use-workspace-dependency.enabled = true,
                use-workspace-dependency.enabled                      = true,
            },
            completion       = {
                path.enabled = true,
            },
            document-link    = {
                pypi-org.enabled       = true,
                pyproject-toml.enabled = true,
            },
            goto-declaration = {
                dependency.enabled = true,
                member.enabled     = true,
            },
            goto-definition  = {
                dependency.enabled = true,
                member.enabled     = true,
                path.enabled       = true,
            },
            hover            = {
                dependency-detail.enabled = true,
            },
            inlay-hint       = {
                dependency-version.enabled = true,
            },
        }
    }
    "tombi-toml/tombi"     = {
        lsp = {
            completion      = {
                path.enabled = true,
            },
            document-link   = {
                path.enabled = true,
            },
            goto-definition = {
                path.enabled = true,
            },
            hover.enabled   = true,
        }
    }
