# Generated by Django 4.2.14 on 2024-11-07 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sds_gateway.api_methods.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, max_length=255)),
                ('capture_type', models.CharField(choices=[('drf', 'Digital RF')], default='drf', max_length=255)),
                ('top_level_dir', models.CharField(blank=True, max_length=2048)),
                ('index_name', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('authors', models.TextField(blank=True)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('keywords', models.TextField(blank=True)),
                ('institutions', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('repository', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('provenance', models.JSONField(blank=True, null=True)),
                ('citation', models.JSONField(blank=True, null=True)),
                ('other', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('directory', models.CharField(default='files/', max_length=2048)),
                ('expiration_date', models.DateField(default=sds_gateway.api_methods.models.default_expiration_date)),
                ('file', models.FileField(upload_to='files/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('media_type', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('permissions', models.CharField(default='rw-r--r--', max_length=9)),
                ('size', models.IntegerField(blank=True)),
                ('sum_blake3', models.CharField(blank=True, max_length=64)),
                ('bucket_name', models.CharField(default='spectrumx', max_length=255)),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api_methods.capture')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api_methods.dataset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
