# Generated by Django 4.2.14 on 2024-10-02 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sds_gateway.api_methods.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureMetadata',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture_type', models.CharField(choices=[('digital_rf', 'Digital RF'), ('sig_mf', 'SigMF')], max_length=20)),
                ('date_captured', models.DateTimeField()),
                ('channel', models.CharField(max_length=255)),
                ('bound_start', models.IntegerField()),
                ('bound_end', models.IntegerField()),
                ('H5Tget_class', models.IntegerField()),
                ('H5Tget_size', models.IntegerField()),
                ('H5Tget_order', models.IntegerField()),
                ('H5Tget_precision', models.IntegerField()),
                ('H5Tget_offset', models.IntegerField()),
                ('subdir_cadence_secs', models.IntegerField()),
                ('file_cadence_millisecs', models.IntegerField()),
                ('sample_rate_numerator', models.IntegerField()),
                ('sample_rate_denominator', models.IntegerField()),
                ('samples_per_second', models.IntegerField()),
                ('is_complex', models.BooleanField()),
                ('is_continuous', models.BooleanField()),
                ('epoch', models.DateTimeField(default=sds_gateway.api_methods.models.unix_epoch_time)),
                ('digital_rf_time_description', models.CharField(max_length=255)),
                ('digital_rf_version', models.CharField(max_length=255)),
                ('center_freq', models.IntegerField()),
                ('span', models.IntegerField()),
                ('gain', models.FloatField()),
                ('resolution_bandwidth', models.IntegerField()),
                ('antenna', models.CharField(max_length=255)),
                ('indoor_outdoor', models.CharField(max_length=255)),
                ('antenna_direction', models.FloatField()),
                ('custom_attrs', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('institutions', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateTimeField(blank=True)),
                ('repository', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('provenance', models.JSONField(blank=True)),
                ('citation', models.JSONField(blank=True)),
                ('other', models.JSONField(blank=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('directory', models.CharField(max_length=2048)),
                ('media_type', models.CharField(default='application/x-hdf5', max_length=255)),
                ('permissions', models.CharField(default='rwxrwxrwx', max_length=255)),
                ('size', models.IntegerField(blank=True)),
                ('sum_blake3', models.CharField(blank=True, max_length=64)),
                ('bucket_name', models.CharField(default='spectrumx', max_length=255)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_methods.dataset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_methods.file')),
                ('unix_time_code', models.IntegerField()),
                ('sequence_num', models.IntegerField()),
                ('init_utc_timestamp', models.DateTimeField()),
                ('computer_time', models.DateTimeField()),
                ('metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_methods.capturemetadata')),
            ],
            options={
                'abstract': False,
            },
            bases=('api_methods.file',),
        ),
    ]
