# Generated by Django 4.2.14 on 2025-01-21 14:01

from django.db import migrations, models
import sds_gateway.api_methods.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0002_alter_dataset_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capture',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capture',
            name='origin',
            field=models.CharField(choices=[(sds_gateway.api_methods.models.CaptureOrigin['System'], 'System'), (sds_gateway.api_methods.models.CaptureOrigin['User'], 'User')], default=sds_gateway.api_methods.models.CaptureOrigin['User'], max_length=255),
        ),
        migrations.AddField(
            model_name='dataset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capture',
            name='capture_type',
            field=models.CharField(choices=[(sds_gateway.api_methods.models.CaptureType['DigitalRF'], 'Digital RF'), (sds_gateway.api_methods.models.CaptureType['RadioHound'], 'RadioHound'), (sds_gateway.api_methods.models.CaptureType['SigMF'], 'SigMF')], default=sds_gateway.api_methods.models.CaptureType['DigitalRF'], max_length=255),
        ),
    ]
