# Generated by Django 4.2.14 on 2025-02-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0003_capture_deleted_at_capture_is_deleted_capture_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='scan_group',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
