# Generated by Django 4.2.14 on 2025-06-19 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_methods', '0005_capture_dataset_capture_is_public_dataset_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryZipFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('files_processed', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('is_downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_zip_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
