# Generated by Django 4.2.14 on 2025-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0006_temporaryzipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
