# Generated by Django 4.2.14 on 2025-06-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0006_temporaryzipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='channel',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
