# Generated by Django 4.2.14 on 2025-07-08 20:00

from django.db import migrations
from pathlib import Path


def populate_capture_names(apps, schema_editor):
    """Populate the name field for existing captures."""
    Capture = apps.get_model('api_methods', 'Capture')
    
    for capture in Capture.objects.filter(name__in=['', None]):
        if capture.top_level_dir:
            # Extract the last part of the path as the name
            path = Path(capture.top_level_dir)
            capture.name = path.name or path.parts[-1] if path.parts else ''
        else:
            # Leave empty for captures without top_level_dir
            capture.name = ''
        
        capture.save(update_fields=['name'])


def reverse_populate_capture_names(apps, schema_editor):
    """Reverse the population by clearing the name field."""
    Capture = apps.get_model('api_methods', 'Capture')
    Capture.objects.update(name='')


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0007_add_capture_name_field'),
    ]

    operations = [
        migrations.RunPython(
            populate_capture_names,
            reverse_populate_capture_names,
        ),
    ] 