# Generated by Django 4.2.14 on 2025-07-11 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sds_gateway.api_methods.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_methods', '0009_capture_shared_with_dataset_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSharePermission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[(sds_gateway.api_methods.models.ItemType['DATASET'], 'Dataset'), (sds_gateway.api_methods.models.ItemType['CAPTURE'], 'Capture')], max_length=20)),
                ('item_uuid', models.UUIDField()),
                ('message', models.TextField(blank=True)),
                ('notified', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_share_permissions', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_share_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['item_type', 'item_uuid'], name='api_methods_item_ty_5619a5_idx'), models.Index(fields=['shared_with', 'item_type'], name='api_methods_shared__855a80_idx'), models.Index(fields=['owner', 'item_type'], name='api_methods_owner_i_09dc7e_idx')],
                'unique_together': {('owner', 'shared_with', 'item_type', 'item_uuid')},
            },
        ),
    ]
