# Generated by Django 4.2.14 on 2025-08-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0011_postprocesseddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postprocesseddata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Post processed data'},
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True),
        ),
    ]
