# Generated by Django 4.2.14 on 2025-08-15 14:26

from django.db import migrations


def update_published_to_final(apps, schema_editor):
    """Update any existing datasets with 'published' status to 'final' status."""
    Dataset = apps.get_model('api_methods', 'Dataset')
    Dataset.objects.filter(status='published').update(status='final')


def reverse_update_published_to_final(apps, schema_editor):
    """Reverse the migration: update 'final' status back to 'published'."""
    Dataset = apps.get_model('api_methods', 'Dataset')
    Dataset.objects.filter(status='final').update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0011_add_dataset_status'),
    ]

    operations = [
        migrations.RunPython(
            update_published_to_final,
            reverse_update_published_to_final,
        ),
    ]
