# Generated by Django 4.2.14 on 2025-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0011_postprocesseddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprocesseddata',
            name='data_file',
            field=models.FileField(blank=True, help_text='File containing the processed data', null=True, upload_to='post_processed_data/'),
        ),
    ]
