# Generated by Django 4.2.14 on 2025-08-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0012_alter_postprocesseddata_data_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprocesseddata',
            name='pipeline_step',
        ),
    ]
