# Generated by Django 4.2.14 on 2025-08-14 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_methods', '0012_alter_postprocesseddata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharegroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_share_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
