# Generated by Django 4.2.14 on 2025-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0013_dataset_status'),
    ]

    replaces = [('api_methods', '0012_alter_postprocesseddata_options_alter_file_size'), ('api_methods', '0013_temporaryzipfile_creation_status')]

    operations = [
        migrations.AddField(
            model_name='temporaryzipfile',
            name='creation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True),
        ),
    ]
