# Generated by Django 4.2.14 on 2025-09-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0014_temporaryzipfile_creation_status_alter_file_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostProcessedData',
            new_name='DEPRECATEDPostProcessedData',
        ),
        migrations.AlterModelOptions(
            name='deprecatedpostprocesseddata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Post processed data (deprecated)'},
        ),
        migrations.RenameIndex(
            model_name='deprecatedpostprocesseddata',
            new_name='api_methods_capture_2535c9_idx',
            old_name='api_methods_capture_beb528_idx',
        ),
        migrations.RenameIndex(
            model_name='deprecatedpostprocesseddata',
            new_name='api_methods_process_f003e0_idx',
            old_name='api_methods_process_fd0607_idx',
        ),
        migrations.RenameIndex(
            model_name='deprecatedpostprocesseddata',
            new_name='api_methods_pipelin_4e9540_idx',
            old_name='api_methods_pipelin_c1ced1_idx',
        ),
    ]
