# Generated by Django 4.2.14 on 2025-08-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0014_temporaryzipfile_creation_status_alter_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersharepermission',
            name='permission_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('co-owner', 'Co-Owner')], default='viewer', max_length=20),
        ),
    ]
