# Generated by Django 4.2.14 on 2025-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0015_rename_postprocesseddata_deprecatedpostprocesseddata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersharepermission',
            name='permission_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('co-owner', 'Co-Owner')], default='viewer', max_length=20),
        ),
    ]
