# Generated by Django 4.2.20 on 2026-04-14 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                        ],
                        max_length=16,
                    ),
                ),
                ("checked_at", models.DateTimeField(db_index=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("detail", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-checked_at", "service_name"],
                "indexes": [
                    models.Index(
                        fields=["service_name", "-checked_at"],
                        name="monitoring_s_service_67efd0_idx",
                    ),
                    models.Index(
                        fields=["status", "-checked_at"],
                        name="monitoring_s_status_62c2e9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemHealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_at", models.DateTimeField(db_index=True)),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                        ],
                        max_length=16,
                    ),
                ),
                ("child_statuses", models.JSONField(default=dict)),
            ],
            options={"ordering": ["-checked_at"]},
        ),
    ]
