[http.routers]

    [http.routers.traefik-api]
        middlewares = ["auth"]
        rule        = "Host(`sds-dev.crc.nd.edu`) && ( PathPrefix(`/dashboard/`) )"
        service     = "api@internal"

        [http.routers.traefik-api.tls]
            certResolver = "letsencrypt"

    [http.routers.sds-gateway-local-app]
        entryPoints = ["web", "web-secure"]
        middlewares = ["csrf"]
        rule        = "Host(`sds-dev.crc.nd.edu`)"
        service     = "sds-gateway-local-app"

        [http.routers.sds-gateway-local-app.tls]
            certResolver = "letsencrypt"

    [http.routers.sds-gateway-prod-app-secure]
        entryPoints = ["web", "web-secure"]
        middlewares = ["csrf", "whitelist-svi-domains"]
        rule        = "Host(`sds.crc.nd.edu`) && Path(`/users/get-svi-api-key/`)"
        service     = "sds-gateway-prod-app"

        [http.routers.sds-gateway-prod-app-secure.tls]
            certResolver = "letsencrypt"

    [http.routers.sds-gateway-prod-app]
        entryPoints = ["web", "web-secure"]
        middlewares = ["csrf"]
        rule        = "Host(`sds.crc.nd.edu`)"
        service     = "sds-gateway-prod-app"

        [http.routers.sds-gateway-prod-app.tls]
            certResolver = "letsencrypt"

    [http.routers.sds-gateway-local-nginx]
        entryPoints = ["web", "web-secure"]
        rule        = "Host(`sds-dev.crc.nd.edu`) && PathPrefix(`/static/`)"
        service     = "sds-gateway-local-nginx"

        [http.routers.sds-gateway-local-nginx.tls]
            certResolver = "letsencrypt"

    [http.routers.sds-gateway-prod-nginx]
        entryPoints = ["web", "web-secure"]
        rule        = "Host(`sds.crc.nd.edu`) && PathPrefix(`/static/`)"
        service     = "sds-gateway-prod-nginx"

        [http.routers.sds-gateway-prod-nginx.tls]
            certResolver = "letsencrypt"

[http.middlewares]
    [http.middlewares.csrf]
        [http.middlewares.csrf.headers]
            hostsProxyHeaders = ["X-CSRFToken"]

    [http.middlewares.whitelist-svi-domains]
        [http.middlewares.whitelist-svi-domains.ipWhiteList]
            sourceRange = [
                "127.0.0.1/32",
                "129.74.246.5/32",
                "10.32.8.29/32",
            ]

    [http.middlewares.auth]
        [http.middlewares.auth.basicAuth]
            usersFile = "/etc/traefik/dashboard/credentials.htpasswd"

[http.services]

    [[http.services.sds-gateway-local-app.loadBalancer.servers]]
        url = "http://sds-gateway-local-app:8000"

    [[http.services.sds-gateway-prod-app.loadBalancer.servers]]
        url = "http://sds-gateway-prod-app:18000"

    [[http.services.sds-gateway-local-nginx.loadBalancer.servers]]
        url = "http://sds-gateway-local-nginx:80"

    [[http.services.sds-gateway-prod-nginx.loadBalancer.servers]]
        url = "http://sds-gateway-prod-nginx:80"

    [[http.services.whoami.loadBalancer.servers]]
        url = "http://whoami:2001"
